### ISSUE TITLE
Book (and Article) Question Sorting

### ISSUE THREAD

**Issue by ChasonMindImp** [maltyeva/mindimp-pg#113]
Sorting functionality, possibly akin to what we were talking about with the courses (Week 1 - end as one option, or most recent ones at the top). Also, sorting of questions within weeks.

**Comment by maltyeva** [comment]
done!

**Comment by meagansiu** [comment]
To clarify, is this meant to fix the problem of discussion questions being
inserted out of order? I was still having problems when I was trying to add
questions earlier.

Is it possible for that problem to be fixed soon? :) I haven't been working
on the books lately because of it but Tracy needs me to add about 30 more.

On Sat, May 2, 2015 at 8:30 PM, maltyeva <notifications@github.com> wrote:

> done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98353413>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
Were you adding questions earlier today? I had the questions sorted by week
order earlier this weekend :)

On Mon, May 4, 2015 at 9:55 AM meagansiu <notifications@github.com> wrote:
To clarify, is this meant to fix the problem of discussion questions being
>
> inserted out of order? I was still having problems when I was trying to add
> questions earlier.
>
> Is it possible for that problem to be fixed soon? :) I haven't been working
> on the books lately because of it but Tracy needs me to add about 30 more.
>

**Comment by meagansiu** [comment]
It seems to be a little spotty. I tried one earlier today and it went into
a random location. I just added a couple and they went to the right week,
but to the beginning of the week's question list instead of the end.

Further clarification: is this meant to be an internal sorting algorithm or
an external tool/toggle the instructor can use to arrange questions as
he/she wants (if this question makes sense)? I was just looking at Chason's
original question about having multiple ways to organize articles.

On Mon, May 4, 2015 at 10:06 AM, maltyeva <notifications@github.com> wrote:

> Were you adding questions earlier today? I had the questions sorted by week
> order earlier this weekend :)
>
> On Mon, May 4, 2015 at 9:55 AM meagansiu <notifications@github.com> wrote:
> To clarify, is this meant to fix the problem of discussion questions being
> >
> > inserted out of order? I was still having problems when I was trying to
> add
> > questions earlier.
> >
> > Is it possible for that problem to be fixed soon? :) I haven't been
> working
> > on the books lately because of it but Tracy needs me to add about 30
> more.
> >
> > On Sat, May 2, 2015 at 8:30 PM, maltyeva <notifications@github.com>
> wrote:
> >
> > > done!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98353413
> > >.
> > >
> >
> >
> >
> > --
> > Meagan Siu, B.A. | 萧笑嫣
> > Program Manager and Advisor* | **思脉**MindImp *
> > http://www.mindimp.com.cn/
> > https://www.mindimp.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98566398
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98567163>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
Ohh I see what you mean> I think i was just sorting by week and not the
chapters. Would you mind sending me an example? That would help sort things
out!

**Comment by meagansiu** [comment]
[image: Inline image 1]

These are sample questions for Shiloh ("question 2" was added following
"question"). Some questions might refer specifically to chapters earlier in
the reading assignment, so ideally they could be sorted chronologically by
week.

On Mon, May 4, 2015 at 10:30 AM, maltyeva <notifications@github.com> wrote:

> Ohh I see what you mean> I think i was just sorting by week and not the
> chapters. Would you mind sending me an example? That would help sort things
> out!
>
>
> On Mon, May 4, 2015 at 10:12 AM meagansiu <notifications@github.com>
> wrote:
>
> > It seems to be a little spotty. I tried one earlier today and it went
> into
> > a random location. I just added a couple and they went to the right week,
> > but to the beginning of the week's question list instead of the end.
> >
> > Further clarification: is this meant to be an internal sorting algorithm
> or
> > an external tool/toggle the instructor can use to arrange questions as
> > he/she wants (if this question makes sense)? I was just looking at
> Chason's
> > original question about having multiple ways to organize articles.
> >
> > On Mon, May 4, 2015 at 10:06 AM, maltyeva <notifications@github.com>
> > wrote:
> >
> > > Were you adding questions earlier today? I had the questions sorted by
> > week
> > > order earlier this weekend :)
> > >
> > > On Mon, May 4, 2015 at 9:55 AM meagansiu <notifications@github.com>
> > wrote:
> > > To clarify, is this meant to fix the problem of discussion questions
> > being
> > > >
> > > > inserted out of order? I was still having problems when I was trying
> to
> > > add
> > > > questions earlier.
> > > >
> > > > Is it possible for that problem to be fixed soon? :) I haven't been
> > > working
> > > > on the books lately because of it but Tracy needs me to add about 30
> > > more.
> > > >
> > > > On Sat, May 2, 2015 at 8:30 PM, maltyeva <notifications@github.com>
> > > wrote:
> > > >
> > > > > done!
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98353413
> > > > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Meagan Siu, B.A. | 萧笑嫣
> > > > Program Manager and Advisor* | **思脉**MindImp *
> > > > http://www.mindimp.com.cn/
> > > > https://www.mindimp.com/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98566398
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98567163
> > >.
> > >
> >
> >
> >
> > --
> > Meagan Siu, B.A. | 萧笑嫣
> > Program Manager and Advisor* | **思脉**MindImp *
> > http://www.mindimp.com.cn/
> > https://www.mindimp.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98567473
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maltyeva/mindimp-pg/issues/113#issuecomment-98569424>.
>



-- 
Meagan Siu, B.A. | 萧笑嫣
Program Manager and Advisor* | **思脉**MindImp *
http://www.mindimp.com.cn/
https://www.mindimp.com/

**Comment by maltyeva** [comment]
Sorry, would you mind resending? The image didn't transfer from email to Github

**Comment by meagansiu** [comment]
![screen shot 2015-05-04 at 10 32 44 am](https://cloud.githubusercontent.com/assets/11342426/7449169/85990c30-f262-11e4-87d2-c4d0a6d321b1.png)

**Comment by maltyeva** [comment]
Ok, per our conversation just now, I added sorting within a week based on an arbitrary column. I also did some re-routing to have redirects to the book/article page when creating discussion questions.
